# Generated by Django 3.2 on 2021-07-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('FA', 'Fashion'), ('TO', 'Toys'), ('HO', 'Home'), ('VE', 'Vehicles')], default='cat', max_length=300),
        ),
    ]
