# Generated by Django 3.2 on 2021-07-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Home', 'Home'), ('Vehicles', 'Vehicles')], default='cat', max_length=300),
        ),
    ]
