# Generated by Django 3.2 on 2021-08-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='auctions_in_the_watchlist', to='auctions.Listing'),
        ),
    ]
